spring:
  application:
    name: bank-app
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_app_db
    username: postgres
    password: postgres

kafka:
  bootstrap-servers: PLAINTEXT_HOST://localhost:9093,PLAINTEXT_HOST://localhost:9094,PLAINTEXT_HOST://localhost:9095
  transaction-id: "your-unique-id"

